.Dd January 14, 2012
.Dt CVSCVT 1
.Sh NAME
.Nm cvscvt
.Nd CVS/RCS to git and svn converter
.Sh SYNOPSIS
.Nm
.Op Fl e Ar email\-domain
.Op Fl f Cm git | Cm svn
.Op Fl K
.Op Fl k Ar keyword
.Op Fl s Ar split\-threshold Ns Op Cm s Ns | Ns Cm m Ns | Ns Cm h Ns | Ns Cm d
.Op Fl T Ar trunk\-name
.Op Fl t Ar tags\-name
.Op Fl v
.Ar path ...
.Sh DESCRIPTION
.Nm
reads in a set of directory trees containing RCS files (suffix
.Cm ,v )
and converts them to a git fast\-import or svn dump.
File revisions are grouped to change sets by author and commit log.
.Pp
Any number of paths may be given, which will be placed at the root of the resulting tree.
If a path ends in a slash, its contents will be placed at the root, otherwise this directory will be placed at the root.
It is also allowed to specify single
.Cm ,v
files.
.Sh OPTIONS
.Bl -tag
.It Fl e Ar email\-domain
Set the email\-domain of the authors and committers.
This option is only valid for git output.
The default is
.Cm invalid .
.It Fl f Cm git | Cm svn
Select the dump output format.
The default is
.Cm git .
.It Fl K
Do not unexpand the default RCS keywords
.Cm Author ,
.Cm Date ,
.Cm Header ,
.Cm Id ,
.Cm Locker ,
.Cm Log ,
.Cm Name ,
.Cm RCSfile ,
.Cm Revision ,
.Cm Source
and
.Cm State .
.It Fl k Ar keyword
Unexpand the given keyword.
No unexpansion is performed on files with the substition modes
.Cm b
and
.Cm o .
.It Fl s Ar split\-threshold Ns Op Cm s Ns | Ns Cm m Ns | Ns Cm h Ns | Ns Cm d
If a potential change set contains a gap longer than this threshold between two consecutive time stamps, then the change set is split at this point.
An optional suffix for
.Cm s Ns econds ,
.Cm m Ns inutes ,
.Cm h Ns ours
or
.Cm d Ns ays
may be appended.
If no suffix is given, the threshold is interpreted as
.Cm seconds.
The default is
.Cm 300\~seconds .
.It Fl T Ar trunk\-name
Set the name for the trunk in the resulting dump.
The default is
.Cm master
for git and
.Cm trunk
for svn.
.It Fl t Ar tags\-name
Set the base name for the tags in the resulting dump.
This is only valid for svn output.
The default is
.Cm tags .
.It Fl v
Show more verbose progress information on stderr.
.El
.Sh EXAMPLES
.D1 git init repo.git
.D1 cvscvt repo.cvs/ | (cd repo.git && git fast\-import)
Import a CVS repository rooted at
.Cm repo.cvs/
into a new git repository rooted at
.Cm repo.git .
The trailing slash is important, so the files in
.Cm repo.cvs/
are placed at the root of the resulting repository.
Otherwise the resulting repository would have one directory
.Cm repo.cvs
at its root.
.Pp
.D1 svnadmin create repo.svn
.D1 cvscvt -f svn repo.cvs/ | svnadmin load repo.svn
This is the same as above except for the target being a svn repository.
.Sh SEE ALSO
.Xr cvs 1 ,
.Xr git\-fast\-import 1 ,
.Xr rcs 1 ,
.Xr svnadmin 1
.Sh AUTHORS
.Nm
was written by
.An Christoph Mallon
.Aq christoph.mallon@gmx.de .
.Sh BUGS
No branches or tags on branches are converted, only trunk and its tags.
In particular vendor branches are not merged into trunk.
This is work in progress.
